name: Build app and deploy to aliyun
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: use Node.js 15.4.0
        uses: actions/setup-node@v2
        with:
          node-version: 15.4.0
      - name: npm install
        run: npm install
      - name: npm build
        run: |
          npm run build
          echo "deb http://archive.debian.org/debian/ stretch main" > /etc/apt/sources.list && \
          echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list && \
          apt update
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        with:
          DEPLOY_KEY: ${{ secrets.AUTO_REFRESH_BLOG_BY_GITHUB_ACTION }}
          ARGS: -avz --delete --exclude='*.pyc'
          SERVER_PORT: "22"
          FOLDER: ./public
          SERVER_IP: ${{ secrets.IP }}
          USERNAME: root
          SERVER_DESTINATION: /usr/local/nginx/html
